#ifndef ZNCONSTANTS_H
#define ZNCONSTANTS_H

#define ZN_APP_TITLE wxT("Lynn Stop Watch")
#define ZN_APP_VERSION    wxT("1.0.0")

enum
{
    ID_ZN_QUIT = 1,
    ID_ZN_FRAME,
    ID_ZN_PANEL,
    ID_ZN_STATIC_TXT_DIGIT_M1,
    ID_ZN_STATIC_TXT_DIGIT_M2,
    ID_ZN_STATIC_TXT_DIGIT_COLON,
    ID_ZN_STATIC_TXT_DIGIT_S1,
    ID_ZN_STATIC_TXT_DIGIT_S2,
    ID_ZN_STATIC_TXT_DIGIT_DOT,
    ID_ZN_STATIC_TXT_DIGIT_U1,
    ID_ZN_TXT_OUTPUT_TEXT,
    ID_ZN_BTN_START_STOP_TIMER,
    ID_ZN_BTN_RESET_LAP_TIMER,
    ID_ZN_BTN_ABOUT,

    ID_ZN_DLG_ABOUT,
    
    ID_ZN_EVENT_TIME_THREAD_TICK,
    ID_ZN_EVENT_TIME_THREAD_COMPLETED
};

#endif
